import numpy as np 

In [1]:
import numpy as np 

****ARRAY OPERATIONS****

Arithmetic operations

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [3]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [4]:
a1-a2

array([-5, -5, -5, -5, -5])

In [5]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [6]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
a1//a2

array([0, 0, 0, 0, 0])

In [8]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [11]:
l = [10,20,30,40]
arr = np.array(l)

In [12]:
arr + 10 

array([20, 30, 40, 50])

In [13]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
arr2 = arr2 + 10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

Deep and Shallow copy

In [15]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
slice = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [17]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
a
b = a.copy()

In [19]:
b[0] = 99 

In [20]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix operations

In [22]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [23]:
A

array([[1, 2],
       [3, 4]])

In [24]:
B

array([[5, 6],
       [7, 8]])

In [25]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [26]:
A

array([[1, 2],
       [3, 4]])

In [27]:
A.T

array([[1, 3],
       [2, 4]])

Advance Array Manipulation

Stacking Array

In [29]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [30]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting array

In [33]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [35]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]